pub mod chat;
mod chat_submission;
mod conversation_row;
pub mod dashboard;
pub mod incognito;
pub mod markdown;
pub mod mcp_panel;
pub mod model_browser;
pub mod picker;
pub mod profile_browser;
pub mod profile_surface;
pub mod profiles_panel;
pub mod reactions;
pub mod sidebar;
mod sidebar_agent_creator;
mod sidebar_shelf;
pub mod slash_commands;
pub mod slash_palette;
pub mod stuck_sessions;
pub mod vault;
